apiVersion: v2
name: growthbook
description: A Helm chart for Kubernetes
type: application
version: draft
appVersion: 2.7.0

dependencies:
  - name: mongodb
    version: 14.6.1
    repository: oci://registry-1.docker.io/bitnamicharts
