---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: kube-state-metrics-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
