---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics-{{ .Release.Name }}
      containers:
      - image: registry.k8s.io/kube-state-metrics/kube-state-metrics:{{ .Chart.AppVersion }}
        name: kube-state-metrics
        ports:
          - containerPort: 8080
