---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kube-state-metrics
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
