---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: prometheus-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
