---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-{{ .Release.Name }}
  labels:
    name: prometheus
  namespace: {{ .Release.Namespace }}
data: {{ .Values.config | toYaml | nindent 2 }}
