---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      {{- if .Values.affinity }}
      affinity: {{ .Values.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: prometheus-{{ .Release.Name }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: prometheus
          image: prom/prometheus:{{ .Chart.AppVersion }}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --log.level=debug
            - --log.format=json
            {{- if .Values.enableFeatureAgent }}
            - --enable-feature=agent
            - --storage.agent.retention.max-time=30m
            {{- else }}
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
            - --storage.tsdb.path=/prometheus/
            - --web.enable-remote-write-receiver
            {{- end }}
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-configmap
              mountPath: /etc/prometheus/
            {{- if .Values.volumes.prometheus }}
            - name: prometheus-pvc
              mountPath: /prometheus/
            {{- end }}
      volumes:
        - name: prometheus-configmap
          configMap:
            name: prometheus-{{ .Release.Name }}
        {{- if .Values.volumes.prometheus }}
        - name: prometheus-pvc
          persistentVolumeClaim:
            {{- if .Values.volumes.prometheus.existingClaim }}
            claimName: {{ .Values.volumes.prometheus.existingClaim }}
            {{- else }}
            claimName: {{ .Values.volumes.prometheus.claimName }}
            {{- end }}
        {{- end }}
