{{- if .Values.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
  annotations: {{ .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-{{ .Release.Name }}
                port:
                  number: 9090
{{- end }}
