{{- if .Values.volumes.prometheus }}
{{- if not .Values.volumes.prometheus.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.prometheus.claimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.volumes.prometheus.acccessModes }}
  storageClassName: {{ .Values.volumes.prometheus.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.volumes.prometheus.size }}
{{- end }}
{{- end }}
