---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
