nameOverride: ~

fullNameOverride: ~

persistence: ~
  # existingClaim: ~
  # storageClassName: longhorn
  # accessModes:
  #   - ReadWriteOnce
  # size: 8Gi

ingress:
  enabled: false
  hosts:
    - host: nexus.example.com
      port: 8081
      name: http
  #   - host: nexus-docker-hosted.example.com
  #     port: 8082
  #     name: docker-hosted
  #   - host: nexus-docker-proxy.example.com
  #     port: 8083
  #     name: docker-proxy
  #   - host: nexus-docker-group.example.com
  #     port: 8084
  #     name: docker-group
  # tlsSecretName: example.com
  # annotations:
  #   traefik.ingress.kubernetes.io/router.entrypoints: websecure

env:
  - name: INSTALL4J_ADD_VM_PARAMS
    value: |
      -Xms2703M -Xmx2703M
      -XX:MaxDirectMemorySize=2703M
      -XX:+UnlockExperimentalVMOptions
      -XX:+UseCGroupMemoryLimitForHeap
      -Djava.util.prefs.userRoot=/nexus-data/javaprefs

tolerations: ~
# tolerations:
#   - effect: NoSchedule
#     key: foo
#     operator: Equal
#     value: bar

affinity: ~
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: foo
#               operator: In
#               values:
#                 - bar
