---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "growthbook.name" . }}
  name: {{ template "growthbook.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "growthbook.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "growthbook.name" . }}
    spec:
      {{- if .Values.growthbook.affinity }}
      affinity: {{ .Values.growthbook.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.growthbook.tolerations }}
      tolerations: {{ .Values.growthbook.tolerations | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: growthbook
          image: growthbook/growthbook:{{ .Chart.AppVersion }}
          {{- if .Values.growthbook.env }}
          env: {{ .Values.growthbook.env | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 3000
            - name: api
              containerPort: 3100
