---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "growthbook.name" . }}
  name: {{ template "growthbook.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: web
      port: 3000
    - name: api
      port: 3100
  selector:
    app: {{ template "growthbook.name" . }}
