---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus
  name: nexus-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: nexus
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      {{- if .Values.affinity }}
      affinity: {{ .Values.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      securityContext:
        runAsGroup: 200
        runAsUser: 200
        fsGroup: 200
      containers:
        - name: nexus
          image: sonatype/nexus3:{{ .Chart.AppVersion }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            {{- range .Values.ingress.hosts }}
            - containerPort: {{ .port }}
            {{- end }}
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          {{- if .Values.env }}
          env: {{ .Values.env | toYaml | nindent 12 }}
          {{- end }}
      volumes:
        - name: nexus-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default .Values.persistence.claimName }}
          {{- else }}
          emptyDir: {}
          {{- end }}
