---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "app.name" . }}
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
    spec:
      {{- if .Values.affinity }}
      affinity: {{ .Values.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      securityContext:
        runAsGroup: 200
        runAsUser: 200
        fsGroup: 200
      containers:
        - name: nexus
          image: sonatype/nexus3:{{ .Chart.AppVersion }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            {{- range .Values.ingress.hosts }}
            - containerPort: {{ .port }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence }}
            - name: nexus-data
              mountPath: /nexus-data
            {{- end }}
          {{- if .Values.env }}
          env: {{ .Values.env | toYaml | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.persistence }}
        - name: nexus-data
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- else }}
            claimName: {{ template "app.fullname" . }}
            {{- end }}
        {{- end }}
