{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nexus
  {{- if .Values.ingress.annotations }}
  annotations: {{ .Values.ingress.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  nexus
                port:
                  number: {{ .port }}
    {{- end }}
{{- end }}
