---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{- range .Values.ingress.hosts }}
    - protocol: TCP
      port: {{ .port }}
      name: {{ .name }}
    {{- end }}
  selector:
    app: {{ template "app.name" . }}
