---
apiVersion: v1
kind: Service
metadata:
  name: nexus-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{- range .Values.ingress.hosts }}
    - protocol: TCP
      port: {{ .port }}
      name: {{ .name }}
    {{- end }}
  selector:
    app: nexus
